### ISSUE TITLE
 Generate new xls error

### ISSUE THREAD

**Issue by thansau239** [Shellntel/luckystrike#26]
Hi @Shellntel,
I already installed excel (2007)... but when i  generate new xls error as bellow
[*] - Generating macro code.
[*] - Adding macro to workbook.
[*] - Embedding payloads into workbook.
[*] - Error occurred creating document. Could not load file or assembly 'Microsoft.Office.Interop.Excel, Version=12.0.0. of its dependencies. The system cannot find the file specified.

Please help me

**Comment by curi0usJack** [comment]
I think the problem is related to your installation of Office. For some reason, you seem to have the regkey for the Office 2010 Excel Interop, but not the dll itself. I have not tested luckystrike with Office 2007, but I would highly recommend you remove office 2007 and go up to 2010+ (preferably 2013/2016).
